Added test_rewards_authority

diff --git a/test/test_set_administrator b/test/test_set_administrator
--- a/test/test_set_administrator
+++ b/test/test_set_administrator
@@ -37,7 +37,6 @@ assert set_administrator_success                                                
 WITHDRAWER_PUBKEY=`solxact pubkey $WITHDRAWER_KEYPAIR`
 WITHDRAWER2_PUBKEY=`solxact pubkey $WITHDRAWER2_KEYPAIR`
 ADMIN_PUBKEY=`solxact pubkey $ADMIN_KEYPAIR`
-
 EXPECTED=`cat <<EOF
 
 Manager Account: $MANAGER_ACCOUNT_PUBKEY
@@ -47,6 +46,12 @@ Operational Authority: $ADMIN_PUBKEY
 Rewards Authority: $ADMIN_PUBKEY
 
 EOF`
+ACTUAL=`$SOURCE/scripts/vamp -u l show $VOTE_ACCOUNT_KEYPAIR`
+if [ "$EXPECTED" != "$ACTUAL" ]; then
+    echo "FAIL: set_administrator_success: Unexpected manager account contents:"
+    diff <(echo "$EXPECTED") <(echo "$ACTUAL")
+    exit 1
+fi
 
 
 # Leave to clean up test
diff --git a/test/test_set_operational_authority b/test/test_set_operational_authority
--- a/test/test_set_operational_authority
+++ b/test/test_set_operational_authority
@@ -44,16 +44,21 @@ WITHDRAWER_PUBKEY=`solxact pubkey $WITHDRAWER_KEYPAIR`
 ADMIN_PUBKEY=`solxact pubkey $ADMIN_KEYPAIR`
 USER_PUBKEY=`solxact pubkey $USER_KEYPAIR`
 OPERATIONS_AUTHORITY_PUBKEY=`solxact pubkey $OPERATIONS_AUTHORITY_KEYPAIR`
-
 EXPECTED=`cat <<EOF
 
 Manager Account: $MANAGER_ACCOUNT_PUBKEY
 Withdraw Authority: $WITHDRAWER_PUBKEY
 Administrator: $ADMIN_PUBKEY
 Operational Authority: $OPERATIONS_AUTHORITY_PUBKEY
-Rewards Authority: $ADMIN_PUBKEY
+Rewards Authority: $USER_PUBKEY
 
 EOF`
+ACTUAL=`$SOURCE/scripts/vamp -u l show $VOTE_ACCOUNT_KEYPAIR`
+if [ "$EXPECTED" != "$ACTUAL" ]; then
+    echo "FAIL: set_operational_authority_success: Unexpected manager account contents:"
+    diff <(echo "$EXPECTED") <(echo "$ACTUAL")
+    exit 1
+fi
 
 
 # Leave to clean up test
diff --git a/test/test_set_rewards_authority b/test/test_set_rewards_authority
--- a/test/test_set_rewards_authority
+++ b/test/test_set_rewards_authority
@@ -44,7 +44,6 @@ WITHDRAWER_PUBKEY=`solxact pubkey $WITHDRAWER_KEYPAIR`
 ADMIN_PUBKEY=`solxact pubkey $ADMIN_KEYPAIR`
 USER_PUBKEY=`solxact pubkey $USER_KEYPAIR`
 REWARDS_AUTHORITY_PUBKEY=`solxact pubkey $REWARDS_AUTHORITY_KEYPAIR`
-
 EXPECTED=`cat <<EOF
 
 Manager Account: $MANAGER_ACCOUNT_PUBKEY
@@ -54,6 +53,12 @@ Operational Authority: $USER_PUBKEY
 Rewards Authority: $REWARDS_AUTHORITY_PUBKEY
 
 EOF`
+ACTUAL=`$SOURCE/scripts/vamp -u l show $VOTE_ACCOUNT_KEYPAIR`
+if [ "$EXPECTED" != "$ACTUAL" ]; then
+    echo "FAIL: set_rewards_authority_success: Unexpected manager account contents:"
+    diff <(echo "$EXPECTED") <(echo "$ACTUAL")
+    exit 1
+fi
 
 
 # Leave to clean up test
